config/routes.rb
Rails.application.routes.draw do
  resources :chef_resources
  resources :programs do
    resources :program_chefs
    put :sort, on: :collection
  end

end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :program_chefs, dependent: :destroy
  has_many :chef_resources, through: :program_chefs
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sort
    program = Program.find(params[:program_id])
    params[:order].each do |key,value|
      if value[:id] != ""
        program.chef_resources.find_by(id: value[:id]).update_attribute(:priority,value[:position])
      end
    end
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:program_name)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
  def expand_collapse_for(chef_resource)
    render html: ExpandCollapse.new(chef_resource).html
  end

  class ExpandCollapse
    def initialize(chef_resource)
      @chef_resource = chef_resource
    end

    def html
      case @chef_resource.resource_type
      when "Repository"
        repository
      when "Deb"
        deb
      when "Source"
        source
      when "Download"
        download
      when "Extract"
        extract
      end
    end

    def repository
      str_temp = ""
      @chef_resource.chef_properties.each do |property|
        str_temp += "<div class='form-group'>"
        str_temp += "  <label for='name'>"
        str_temp += "    Name:"
        str_temp += "  </label>"
        str_temp += "  <div class='input-group'>"
        str_temp += "    <input type='text' name='chef_property_#{property.id}' value='#{property.value}'>"
        str_temp += "  </div>"
        str_temp += "</div>"
      end
      return str_temp.html_safe
    end

    def deb
      str_temp = ""
      @chef_resource.chef_properties.each do |property|
        str_temp += "<div class='form-group'>"
        str_temp += "  <label for='name'>"
        str_temp += "    Name:"
        str_temp += "  </label>"
        str_temp += "  <div class='input-group'>"
        str_temp += "    <input type='text' name='chef_property_#{property.id}' value='#{property.value}'>"
        str_temp += "  </div>"
        str_temp += "</div>"
      end
      return str_temp.html_safe
    end

    def source
      str_temp = ""
      @chef_resource.chef_properties.each do |property|
        str_temp += "<div class='form-group'>"
        str_temp += "  <label for='name'>"
        str_temp += "    Name:"
        str_temp += "  </label>"
        str_temp += "  <div class='input-group'>"
        str_temp += "    <input type='text' name='chef_property_#{property.id}' value='#{property.value}'>"
        str_temp += "  </div>"
        str_temp += "</div>"
      end
      return str_temp.html_safe
    end

    def download
      str_temp = ""
      @chef_resource.chef_properties.each do |property|
        if property.value_type == "name"
          str_temp += "<div class='form-group'>"
          str_temp += "  <label for='name'>"
          str_temp += "    Name:"
          str_temp += "  </label>"
          str_temp += "  <div class='input-group'>"
          str_temp += "    <textarea type='text' name='chef_property_#{property.id}' >#{property.value}</textarea>"
          str_temp += "  </div>"
          str_temp += "</div>"
        else #file_path
          str_temp += "<div class='form-group'>"
          str_temp += "  <label for='name'>"
          str_temp += "    File path:"
          str_temp += "  </label>"
          str_temp += "  <div class='input-group'>"
          str_temp += "    <input type='text' name='chef_property_#{property.id}' value='#{property.value}'>"
          str_temp += "  </div>"
          str_temp += "</div>"
        end
      end
      return str_temp.html_safe
    end

    def extract
      str_temp = ""
      @chef_resource.chef_properties.each do |property|
        if property.value_type == "source"
          str_temp += "<div class='form-group'>"
          str_temp += "  <label for='name'>"
          str_temp += "    Source:"
          str_temp += "  </label>"
          str_temp += "  <div class='input-group'>"
          str_temp += "    <input type='text' name='chef_property_#{property.id}' value='#{property.value}'>"
          str_temp += "  </div>"
          str_temp += "</div>"
        else #destination
          str_temp += "<div class='form-group'>"
          str_temp += "  <label for='name'>"
          str_temp += "    Destination:"
          str_temp += "  </label>"
          str_temp += "  <div class='input-group'>"
          str_temp += "    <textarea type='text' name='chef_property_#{property.id}' >#{property.value}</textarea>"
          str_temp += "  </div>"
          str_temp += "</div>"
        end
      end
      return str_temp.html_safe
    end
  end

end

app/views/programs/_chefresources.html.erb
<div class="chef_resource_fields" data-id="<%= chef.id %>">
<div class="field">
<%= chef.resource_type %>
<div style="display: none;">
  <%= expand_collapse_for(chef) %>
</div>
<button type="button" class="btn chef_property">Expand</button>
<%= link_to 'Edit', edit_chef_resource_path(chef) %>
<%= form_for(@program, :url => "/programs/"+@program.id.to_s+"/program_chefs/"+chef.id.to_s, :method => :delete) do %>
        <%= hidden_field_tag 'program_id', @program.id  %>
        <%= hidden_field_tag 'chef_id', chef.id  %>
        <%= submit_tag "delete", class: "btn btn-default" %>
<% end %>
</div>
</div>

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :program_name %><br>
    <%= f.text_field :program_name %>
  </div>

  <%= hidden_field_tag :program_id, @program.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


  <% if @program.persisted? %>
    <hr>
      <%= form_for(@program, :url => "/programs/"+@program.id.to_s+"/program_chefs", :method => :post) do %>
              <%= hidden_field_tag 'program_id', @program.id  %>
              <%= select_tag :chef_resource_type, options_for_select([["Install from repository", "Repository"], ["Install from deb file", "Deb"], ["Install from source", "Source"]]) %>
              <%= submit_tag "add-install", class: "btn btn-success" %>
      <% end %>
      <%= form_for(@program, :url => "/programs/"+@program.id.to_s+"/program_chefs", :method => :post) do %>
              <%= hidden_field_tag 'program_id', @program.id  %>
              <%= select_tag :chef_resource_type, options_for_select([["Download file", "Download"], ["Extract file", "Extract"]]) %>
              <%= submit_tag "add-file-folder", class: "btn btn-success" %>
      <% end %>
      <h2>Chef resource</h2>
      <div class="sortable">
        <% if @program.chef_resources.any? %>
          <%= render partial: "chefresources", collection: @program.chef_resources, as: :chef %>
        <% end %>
    </div>
    <hr>
  <% end %>
<%= javascript_include_tag "programs/btn_expand_collapse.js"%>
<%= javascript_include_tag "programs/html.sortable.js"%>
<%= javascript_include_tag "programs/sort.js"%>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Programs</h1>

<table>
  <thead>
    <tr>
      <th>Program name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.program_name %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Program name:</strong>
  <%= @program.program_name %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>