config/routes.rb
Rails.application.routes.draw do
  resources :chef_resources
  resources :programs do
    resources :program_chefs
    put :sort, on: :collection
  end

end

app/models/program_chef.rb
class ProgramChef < ActiveRecord::Base
  belongs_to :program
  belongs_to :chef_resource
end

app/controllers/program_chefs_controller.rb
class ProgramChefsController < ApplicationController
  #before_action :set_program_chef, only: [:show, :edit, :update, :destroy]

  # GET /program_chefs
  # GET /program_chefs.json
  def index
    #@program_chefs = ProgramChef.all
  end

  # GET /program_chefs/1
  # GET /program_chefs/1.json
  def show
  end

  # GET /program_chefs/new
  def new
    #@program_chef = ProgramChef.new
  end

  # GET /program_chefs/1/edit
  def edit
  end

  # POST /program_chefs
  # POST /program_chefs.json
  def create
    #@program_chef = ProgramChef.new(program_chef_params)
    @program = Program.find(params[:program_id])
    @chef_resource = ChefResource.new(resource_type: params[:chef_resource_type])

    respond_to do |format|
      if @program.program_chefs.create(chef_resource: @chef_resource)
        format.html { redirect_to edit_program_path(@program), notice: 'Chef resource was successfully created.' }
        format.json { render :show, status: :created, location: edit_program_path(@program) }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /program_chefs/1
  # PATCH/PUT /program_chefs/1.json
  def update
    #respond_to do |format|
      #if @program_chef.update(program_chef_params)
        #format.html { redirect_to @program_chef, notice: 'Program chef was successfully updated.' }
        #format.json { render :show, status: :ok, location: @program_chef }
      #else
        #format.html { render :edit }
        #format.json { render json: @program_chef.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /program_chefs/1
  # DELETE /program_chefs/1.json
  def destroy
    @program = Program.find(params[:program_id])
    @chef_resource = ChefResource.find(params[:chef_id])
    @program.program_chefs.find_by(chef_resource_id: @chef_resource.id).destroy
    #@program_chef.destroy
    respond_to do |format|
      format.html { redirect_to edit_program_path(@program), notice: 'Chef resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_program_chef
      #@program_chef = ProgramChef.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def program_chef_params
      #params[:program_chef]
    #end
end

app/helpers/program_chefs_helper.rb
module ProgramChefsHelper
end

app/views/program_chefs/_form.html.erb
<%= form_for(@program_chef) do |f| %>
  <% if @program_chef.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program_chef.errors.count, "error") %> prohibited this program_chef from being saved:</h2>

      <ul>
      <% @program_chef.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/program_chefs/edit.html.erb
<h1>Editing Program Chef</h1>

<%= render 'form' %>

<%= link_to 'Show', @program_chef %> |
<%= link_to 'Back', program_chefs_path %>

app/views/program_chefs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Program Chefs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @program_chefs.each do |program_chef| %>
      <tr>
        <td><%= link_to 'Show', program_chef %></td>
        <td><%= link_to 'Edit', edit_program_chef_path(program_chef) %></td>
        <td><%= link_to 'Destroy', program_chef, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program chef', new_program_chef_path %>

app/views/program_chefs/new.html.erb
<h1>New Program Chef</h1>

<%= render 'form' %>

<%= link_to 'Back', program_chefs_path %>

app/views/program_chefs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_program_chef_path(@program_chef) %> |
<%= link_to 'Back', program_chefs_path %>