config/routes.rb
Rails.application.routes.draw do
  resources :chef_resources
  resources :programs do
    resources :program_chefs
    put :sort, on: :collection
  end

end

app/models/chef_resource.rb
class ChefResource < ActiveRecord::Base
  has_many :program_chefs, dependent: :destroy
  has_many :programs, through: :program_chefs
  has_many :chef_properties, dependent: :destroy
  accepts_nested_attributes_for :chef_properties
  default_scope { order("priority ASC") }
end

app/controllers/chef_resources_controller.rb
class ChefResourcesController < ApplicationController
  before_action :set_chef_resource, only: [:show, :edit, :update, :destroy]

  # GET /chef_resources
  # GET /chef_resources.json
  def index
    @chef_resources = ChefResource.all
  end

  # GET /chef_resources/1
  # GET /chef_resources/1.json
  def show
  end

  # GET /chef_resources/new
  def new
    @chef_resource = ChefResource.new
  end

  # GET /chef_resources/1/edit
  def edit
    @property_count = 0
    case @chef_resource.resource_type
    when "Repository", "Deb", "Source"
      if !@chef_resource.chef_properties.any?
        @chef_resource.chef_properties.build
      end
    when "Download", "Extract"
      if !@chef_resource.chef_properties.any?
        @chef_resource.chef_properties.build
        @chef_resource.chef_properties.build
      end
    end
  end

  # POST /chef_resources
  # POST /chef_resources.json
  def create
    @chef_resource = ChefResource.new(chef_resource_params)

    respond_to do |format|
      if @chef_resource.save
        format.html { redirect_to @chef_resource, notice: 'Chef resource was successfully created.' }
        format.json { render :show, status: :created, location: @chef_resource }
      else
        format.html { render :new }
        format.json { render json: @chef_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chef_resources/1
  # PATCH/PUT /chef_resources/1.json
  def update
    respond_to do |format|
      if @chef_resource.update(chef_resource_params)
        format.html { redirect_to edit_chef_resource_path(@chef_resource), notice: 'Chef resource was successfully updated.' }
        format.json { render :show, status: :ok, location: edit_chef_resource_path(@chef_resource) }
      else
        format.html { render :edit }
        format.json { render json: @chef_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chef_resources/1
  # DELETE /chef_resources/1.json
  def destroy
    @chef_resource.destroy
    respond_to do |format|
      format.html { redirect_to chef_resources_url, notice: 'Chef resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chef_resource
      @chef_resource = ChefResource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chef_resource_params
      params.require(:chef_resource).permit(:resource_type, chef_properties_attributes: [ :id, :value, :value_type ])
    end
end

app/helpers/chef_resources_helper.rb
module ChefResourcesHelper
end

app/views/chef_resources/_form.html.erb
<%= form_for(@chef_resource) do |f| %>
  <% if @chef_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chef_resource.errors.count, "error") %> prohibited this chef_resource from being saved:</h2>

      <ul>
      <% @chef_resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resource_type %><br>
    <%= f.text_field :resource_type %>
  </div>
  <h2>Chef Properties</h2>
  <div class="chef_properties_fields">
    <div class="field">
      <% %>
      <% case @chef_resource.resource_type %>
      <% when "Repository", "Deb", "Source" %>
        <%= f.fields_for :chef_properties do |property| %>
          <%= property.label :name %><br>
          <%= property.text_field :value %>
          <% if property.object.id != nil %>
            <%= property.hidden_field :value_type %>
          <% else %>
            <%= property.hidden_field :value_type, :value => "name" %>
          <% end %>
        <% end %>
      <% when "Download" %>
        <%= f.fields_for :chef_properties do |property| %>
          <% if @property_count == 0 %>
            <%= property.label :name %><br>
            <%= property.text_area :value %>
            <% if property.object.id != nil %>
              <%= property.hidden_field :value_type %>
            <% else %>
              <%= property.hidden_field :value_type, :value => "name" %>
            <% end %>
          <% else %>
            <%= property.label :file_path %><br>
            <%= property.text_field :value %>
            <% if property.object.id != nil %>
              <%= property.hidden_field :value_type %>
            <% else %>
              <%= property.hidden_field :value_type, :value => "file_path" %>
            <% end %>
          <% end %>
          <% @property_count = @property_count + 1 %>
        <% end %>
      <% when "Extract" %>
        <%= f.fields_for :chef_properties do |property| %>
          <% if @property_count == 0 %>
            <%= property.label :source %><br>
            <%= property.text_field :value %>
            <% if property.object.id != nil %>
              <%= property.hidden_field :value_type %>
            <% else %>
              <%= property.hidden_field :value_type, :value => "source" %>
            <% end %>
          <% else %>
            <%= property.label :destination %><br>
            <%= property.text_area :value %>
            <% if property.object.id != nil %>
              <%= property.hidden_field :value_type %>
            <% else %>
              <%= property.hidden_field :value_type, :value => "destination" %>
            <% end %>
          <% end %>
          <% @property_count = @property_count + 1 %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chef_resources/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing Chef Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @chef_resource %> |
<%= link_to 'Back', chef_resources_path %>
<br>
<% @chef_resource.programs.each do |program| %>
  <%= link_to program.program_name, edit_program_path(program) %><br>
<% end %>

app/views/chef_resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chef Resources</h1>

<table>
  <thead>
    <tr>
      <th>Resource type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chef_resources.each do |chef_resource| %>
      <tr>
        <td><%= chef_resource.resource_type %></td>
        <td><%= link_to 'Show', chef_resource %></td>
        <td><%= link_to 'Edit', edit_chef_resource_path(chef_resource) %></td>
        <td><%= link_to 'Destroy', chef_resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chef resource', new_chef_resource_path %>

app/views/chef_resources/new.html.erb
<h1>New Chef Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', chef_resources_path %>

app/views/chef_resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resource type:</strong>
  <%= @chef_resource.resource_type %>
</p>

<%= link_to 'Edit', edit_chef_resource_path(@chef_resource) %> |
<%= link_to 'Back', chef_resources_path %>